<?php
$recent_posts = get_recent_posts(3);
?>
<!-- Hero -->
<section class="hero">
  <div class="container">
    <div class="hero-content">
      <h1 class="hero-title">Human Data Expertise<br>for the AI Era</h1>
      <p class="hero-sub">
        Real-world insights for data engineers navigating the shift — written by a practitioner,
        not generated by a machine. Career advice, technical depth, and consulting when you need it.
      </p>
      <div class="hero-cta">
        <a href="/blog" class="btn btn-primary">Read the Blog</a>
        <a href="/services" class="btn btn-outline">Consulting Services</a>
      </div>
    </div>
    <div class="hero-logo">
      <img src="/assets/images/data_dinosaur_header.svg" alt="DataDinosaur" class="hero-dino">
    </div>
  </div>
</section>

<!-- Value props -->
<section class="value-props">
  <div class="container">
    <div class="props-grid">
      <div class="prop-card">
        <div class="prop-icon">&#128200;</div>
        <h3>Career Strategy</h3>
        <p>Practical advice on staying relevant and growing your career as gen AI reshapes the data engineering landscape.</p>
      </div>
      <div class="prop-card">
        <div class="prop-icon">&#128736;</div>
        <h3>Technical Depth</h3>
        <p>Governance, metadata management, data quality, responsible AI — the durable skills that matter most right now.</p>
      </div>
      <div class="prop-card">
        <div class="prop-icon">&#128101;</div>
        <h3>1-on-1 Consulting</h3>
        <p>Need expert eyes on your data architecture? Reach out for direct consulting on your specific challenges.</p>
      </div>
    </div>
  </div>
</section>

<!-- Recent blog posts -->
<?php if (!empty($recent_posts)): ?>
<section class="recent-posts">
  <div class="container">
    <div class="section-header">
      <h2>Latest from the Blog</h2>
      <a href="/blog" class="section-link">All posts &rarr;</a>
    </div>
    <div class="post-grid">
      <?php foreach ($recent_posts as $p): ?>
      <?php
        $excerpt = $p['excerpt'] ?: auto_excerpt($p['content'] ?? '', $config['blog']['excerpt_length']);
      ?>
      <article class="post-card">
        <div class="post-card-body">
          <h3 class="post-card-title">
            <a href="/blog/<?= e($p['slug']) ?>"><?= e($p['title']) ?></a>
          </h3>
          <p class="post-card-excerpt"><?= e($excerpt) ?></p>
        </div>
        <div class="post-card-footer">
          <time class="post-meta-date" datetime="<?= e($p['published_at']) ?>">
            <?= date($config['blog']['date_format'], strtotime($p['published_at'])) ?>
          </time>
          <a href="/blog/<?= e($p['slug']) ?>" class="post-read-more">Read &rarr;</a>
        </div>
      </article>
      <?php endforeach; ?>
    </div>
  </div>
</section>
<?php endif; ?>

<!-- CTA banner -->
<section class="cta-banner">
  <div class="container">
    <h2>Have a data challenge?</h2>
    <p>I offer consulting on data architecture, governance, AI integration, and data quality.
       Let's talk about what you're working on.</p>
    <a href="/contact" class="btn btn-primary">Get in Touch</a>
  </div>
</section>
