server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php;

    # Block sensitive files
    location ~ /\.(env|git|yaml|json|sql|md|sh|ini|lock)$ { deny all; return 404; }
    location ~ ^/(src|vendor|scripts)/ { deny all; return 404; }

    location ~* \.(css|js|png|jpg|jpeg|gif|svg|ico|woff|woff2)$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass  php:9000;
        fastcgi_index index.php;
        include       fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO       $fastcgi_path_info;
    }
}
